# frontend_defaults: &defaults
#   docker:
#     - image: circleci/node:12.4.0

# api_defaults: &defaults
#   docker:
#     - image: circleci/ruby:2.5.5-stretch

version: 2
jobs:
  prepare:
    docker:
    - image: circleci/node:12.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
          working_directory: frontend
      - save_cache:
          key: v1-dependencies-{{ checksum "frontend/yarn.lock" }}
          paths: frontend/node_modules
      - persist_to_workspace:
          root: frontend
          paths:
            - node_modules
  lint:
    docker:
    - image: circleci/node:12.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - attach_workspace:
          at: frontend
      - run:
          name: Run ESLint
          command: yarn lint
          working_directory: frontend
  build:
    docker:
    - image: circleci/node:12.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - attach_workspace:
          at: frontend
      - run:
          name: Build
          command: yarn build
          working_directory: frontend
workflows:
  version: 2
  lint_and_build:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - lint
