version: 2
jobs:
  frontend_prepare:
    docker:
    - image: circleci/node:12.4.0
    working_directory: ~/workspace_frontend
    steps:
      - checkout
      - restore_cache:
          key: ohapo-frontend-v1-dependencies-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
          working_directory: frontend
      - save_cache:
          key: ohapo-frontend-v1-dependencies-{{ checksum "frontend/yarn.lock" }}
          paths: frontend/node_modules
      - persist_to_workspace:
          root: frontend
          paths:
            - node_modules
  frontend_lint:
    docker:
    - image: circleci/node:12.4.0
    working_directory: ~/workspace_frontend
    steps:
      - checkout
      - attach_workspace:
          at: frontend
      - run:
          name: Run ESLint
          command: yarn lint
          working_directory: frontend
  frontend_build:
    docker:
    - image: circleci/node:12.4.0
    working_directory: ~/workspace_frontend
    steps:
      - checkout
      - attach_workspace:
          at: frontend
      - run:
          name: Build
          command: yarn build
          working_directory: frontend
  api_build:
    working_directory: ~/workspace_api
    docker:
      - image: circleci/ruby:2.6.4-stretch
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      # Restore bundle cache
      - restore_cache:
          keys:
          - ohapo-api-bundle-v1-{{ checksum "api/src/Gemfile.lock" }}
          - ohapo-api-bundle-v1-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
          working_directory: api/src
      # Store bundle cache
      - save_cache:
          key: ohapo-api-bundle-v1-{{ checksum "api/src/Gemfile.lock" }}
          paths:
            - api/src/vendor/bundle
      - run:
          name: Setup dockerize
          command: bash .circleci/setup-dockerize.sh
      - run:
          name: wait mysql
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: create databse
          command: bundle exec rails db:create
          working_directory: api/src
      - run:
          name: migrate databse
          command: bundle exec rails db:migrate
          working_directory: api/src
  api_rubocop:
    working_directory: ~/workspace_api
    docker:
      - image: circleci/ruby:2.6.4-stretch
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
      - run:
          name: Rubocop
          command: bundle exec rubocop
  api_test:
    working_directory: ~/workspace_api
    docker:
      - image: circleci/ruby:2.6.4-stretch
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - run:
          name: rspec test
          command: bundle exec rspec
          working_directory: api/src
workflows:
  version: 2
  lint_and_build:
    jobs:
      - frontend_prepare
      - frontend_lint:
          requires:
            - frontend_prepare
      - frontend_build:
          requires:
            - frontend_lint
      - api_build
      - api_rubocop:
        requires:
          - api_build
      - api_test:
        requires:
          - api_rubocop
