version: 2
jobs:
  build:
    machine:
      image: &circleci_image circleci/classic:edge
    working_directory: &wd ~/repo
    steps:
      - checkout
      - run:
          name: cp env
          command: cp frontend/.env.default frontend/.env && cp .env.default .env && cp api/src/.env.default api/src/.env
      - run:
          name: docker-compose -f ./docker-compose-circleci.yml build
          command: |
            set -x
            docker-compose -f ./docker-compose-circleci.yml build
      - run:
          name: docker-compose -f ./docker-compose-circleci.yml run --rm api bundle install
          command: |
            set -x
            docker-compose -f ./docker-compose-circleci.yml run --rm api bundle install
      # - run:
      #     name: docker-compose up
      #     command: |
      #       set -x
      #       docker-compose up

  staticAnalysisApi:
    machine:
      image: *circleci_image
    working_directory: *wd
    steps:
      - run:
          name: docker-compose -f ./docker-compose-circleci.yml run --rm api rubocop
          command: |
            set -x
            docker-compose -f ./docker-compose-circleci.yml run --rm api rubocop

  testApi:
    machine:
      image: *circleci_image
    working_directory: *wd
    steps:
      - run:
          name: docker-compose up -f ./docker-compose-circleci.yml
          command: |
            set -x
            docker-compose up -f ./docker-compose-circleci.yml
      - run:
          name: docker-compose -f ./docker-compose-circleci.yml run --rm api rspec
          command: |
            set -x
            docker-compose -f ./docker-compose-circleci.yml run --rm api rspec
      - run:
          name: docker-compose -f ./docker-compose-circleci.yml down
          command: docker-compose -f ./docker-compose-circleci.yml down

  staticAnalysisFrontend:
    machine:
      image: *circleci_image
    working_directory: *wd
    steps:
      - run:
          name: docker-compose -f ./docker-compose-circleci.yml exec builder yarn lint
          command: |
            set -x
            docker-compose -f ./docker-compose-circleci.yml exec builder yarn lint

workflows:
  version: 2
  test_and_analyse:
    jobs:
      - &build build
      - testApi:
          requires:
            - *build
      - staticAnalysisApi:
          requires:
            - *build
      - staticAnalysisFrontend:
          requires:
            - *build
