swagger: "2.0"
info:
  description: "This is a sample"
  version: 1.0.0
  title: Swagger Sample
tags:
  - name: sample
    description: sample api
schemes:
  - http
paths:
  /sample:
    get:
      tags:
        - sample
      summary: sample api
      x-swagger-router-controller: SampleController
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: "http://petstore.swagger.io/api/oauth/dialog"
    flow: implicit
    scopes:
      "write:pets": modify pets in your account
      "read:pets": read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Sample:
    properties:
      id:
        type: integer
        example: 123
