openapi: "3.0.2"

info:
  title: "ohapo API"
  version: "0.0.1"

servers:
  - url: "http://localhost:3031/"
    description: "ローカル環境 API"

# API仕様一覧
paths:
  "/categories":
    get:
      tags:
        - categories
      summary: "ユーザが選択できるカテゴリの一覧を返す"
      parameters: []
      responses:
        "200":
          description: "Categoryモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
                example:
                  - id: 1
                    category_name: カテゴリ1
                  - id: 2
                    category_name: カテゴリ2
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/whatdays":
    get:
      tags:
        - whatdays
      summary: "昨日、今日、明日の記念日を返す"
      parameters: []
      responses:
        "200":
          description: "Whatdayモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Whatday"
                example:
                  - date: "2019-09-20"
                    description: "バスの日"
                  - date: "2019-09-21"
                    description: "ファッションショーの日"
                  - date: "2019-09-22"
                    description: "ワンウェブデー"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/user/{userId}":
    get:
      tags:
        - user
      summary: "ユーザ情報を返す"
      parameters:
        - name: userId
          in: path # パラメータをパス内に含める
          description: "ユーザID"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "ユーザモデル"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/User"
                example:
                  - date: "2019-09-20"
                    description: "バスの日"
                  - date: "2019-09-21"
                    description: "ファッションショーの日"
                  - date: "2019-09-22"
                    description: "ワンウェブデー"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "user/create":
    post:
      tags:
        - user
      summary: "ユーザ情報を登録する"
      parameters: []
      responses:
        "200":
          description: "Whatdayモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Whatday"
                example:
                  - date: "2019-09-20"
                    description: "バスの日"
                  - date: "2019-09-21"
                    description: "ファッションショーの日"
                  - date: "2019-09-22"
                    description: "ワンウェブデー"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/user/{userId}/update":
    patch:
      tags:
        - user
      summary: "ユーザ情報を更新する"
      parameters: []
      responses:
        "200":
          description: "Whatdayモデルのリスト"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Whatday"
                example:
                  - date: "2019-09-20"
                    description: "バスの日"
                  - date: "2019-09-21"
                    description: "ファッションショーの日"
                  - date: "2019-09-22"
                    description: "ワンウェブデー"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/user/{userId}/delete":
    delete:
      tags:
        - user
      summary: "ユーザ情報を消す"
      parameters: []
      responses:
        "200":
          description: "Whatdayモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Whatday"
                example:
                  - date: "2019-09-20"
                    description: "バスの日"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/healthcheck":
    get:
      tags:
        - healthcheck
      summary: "正常ならOKを返す"
      responses:
        "200":
          description: "正常"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/HealthCheck"
        "400":
          $ref: "#/components/responses/UnexpectedError"

# 扱うコンポーネント一覧
components:
  schemas:
    Category:
      description: "カテゴリ"
      type: object
      required: #必須フィールド
        - id
        - category_name
      properties:
        id:
          type: integer
        category_name:
          type: string
    
    Whatday:
      description: "記念日"
      type: object
      required:
        - date
        - description
      properties:
        date:
          type: string
          format: date
        description:
          type: string

    User:
      description: "ユーザ"
      type: object
      required:
        - id
        - user_name
        - age
        - gender
        - location
        - zip_code
      properties:
        id:
          type: integer
          example: 101
        user_name:
          type: string
          example: "ワン　チャン"
        age:
          type: integer
          example: 10
        gender:
          type: string
          example: "男"
        location:
          type: string
          example: "東京都品川区"
        zip_code:
          type: string
          pattern: "¥d{3}-¥d{4}"
          example: "123-4567"
    Error:
      description: "エラー"
      type: object
      required:
        - message
        - code
      properties:
        message:
          title: "Err Msg"
          type: string
          example: "予期しないエラーです"
        code:
          title: "Status Code"
          type: integer
          minimum: 100
          maximum: 600
          example: 400
    HealthCheck:
      description: "HealthCheck"
      type: object
      required:
        - result
      properties:
        result:
          title: "result"
          type: string
          example: "ok"


  # 汎用的に使うものはまとめておく
  responses:
    UnexpectedError:
      description: "予期しないエラー"
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Error"

tags:
  - name: categories
    description: "カテゴリ一覧機能"
  - name: whatdays
    description: "記念日機能"
  - name: user
    description: "ユーザ操作機能"
  - name: healthcheck
    description: "HealthCheck機能"
