openapi: "3.0.2"

info:
  title: "ohapo API"
  version: "0.0.1"

servers:
  - url: "http://localhost:3031/"
    description: "ローカル環境 API"

# API仕様一覧
paths:
  "/category":
    get:
      tags:
        - category
      summary: "ユーザが選択できるカテゴリの一覧を返す"
      parameters: []
      responses:
        "200":
          description: "Categoryモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
                example:
                  - id: 1
                    name: カテゴリ1
                  - id: 2
                    name: カテゴリ2
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/healthcheck":
    get:
      tags:
        - healthcheck
      summary: "正常ならOKを返す"
      responses:
        "200":
          description: "正常"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/HealthCheck"
        "400":
          $ref: "#/components/responses/UnexpectedError"

# 扱うコンポーネント一覧
components:
  schemas:
    Category:
      description: "カテゴリ"
      type: object
      required: #必須フィールド
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Error:
      description: "エラー"
      type: object
      required:
        - message
        - code
      properties:
        message:
          title: "Err Msg"
          type: string
          example: "予期しないエラーです"
        code:
          title: "Status Code"
          type: integer
          minimum: 100
          maximum: 600
          example: 400
    HealthCheck:
      description: "HealthCheck"
      type: object
      required:
        - result
      properties:
        result:
          title: "result"
          type: string
          example: "ok"


  # 汎用的に使うものはまとめておく
  responses:
    UnexpectedError:
      description: "予期しないエラー"
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Error"

tags:
  - name: category
    description: "カテゴリ一覧機能"
  - name: healthcheck
    description: "HealthCheck機能"
